import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const font = localFont({ src: "../../public/font.woff" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
